<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:requestns="http://distributoricarburanti.domest.sogei.it" xmlns:responsens="http://ws.sogei.it/output/" xmlns:errorns="http://distributoricarburanti.domest.sogei.it" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://distributoricarburanti.domest.sogei.it/services/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://distributoricarburanti.domest.sogei.it/services/">
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://distributoricarburanti.domest.sogei.it" schemaLocation="definitorio.xsd"/>
			<xsd:import namespace="http://ws.sogei.it/output/" schemaLocation="esitoServizi.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="Output">
		<wsdl:part name="Output" element="responsens:Output"/>
	</wsdl:message>
	<wsdl:message name="Input">
		<wsdl:part name="Input" element="requestns:Input"/>
	</wsdl:message>
	<wsdl:portType name="ContabilitaDistributoriCarburanti">
		<wsdl:operation name="process">
			<wsdl:input message="tns:Input"/>
			<wsdl:output message="tns:Output"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ContabilitaDistributoriCarburantiSoapBinding" type="tns:ContabilitaDistributoriCarburanti">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="process">
			<soap:operation soapAction="http://process.distributoricarburanti.domest.sogei.it/wsdl/ContabilitaDistributoriCarburanti"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ContabilitaDistributoriCarburanti">
		<wsdl:port name="ContabilitaDistributoriCarburantiService" binding="tns:ContabilitaDistributoriCarburantiSoapBinding">
			<soap:address location="https://interoptest.agenziadoganemonopoli.gov.it/ContabilitaDistributoriCarburantiWeb/services/ContabilitaDistributoriCarburanti"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>